### ISSUE TITLE
[Feature Request] Ability to send emails using Gmail SMTP

### ISSUE THREAD

**Issue by rizvi-wedevs** [weDevsOfficial/wemail#13]
Other plugins are giving this option. Such as WP Mail.

More info here: [https://wpforms.com/how-to-securely-send-wordpress-emails-using-gmail-smtp/]

**Comment by ashikCodecamper** [comment]
[
![screenshot 2019-02-07 at 6 04 24 pm](https://user-images.githubusercontent.com/15714023/52410701-66235a80-2b03-11e9-96f7-43281a64696d.png)
](url)

# use google app password generator. gmail does not support direct password over smtp

**Comment by tareq1988** [comment]
We could create an app for google and authenticate the user to that app. That way we could send email for that user. We have [done similar things](https://wperp.com/docs/crm/tutorials/how-to-configure-gmail-api-connection-in-the-crm-settings/) in WP ERP.
