### ISSUE TITLE
Getting fatal on my-account page error when activating

### ISSUE THREAD

**Issue by nayemDevs** [weDevsOfficial/wemail#45]
Kindly check this screenshot to check- https://prnt.sc/p0mrtq. I have just activated weMail plugin and on the my-account page, it is showing the above error.

**Comment by AshiqKiron** [comment]
Faced the same error on Blog post listing page, single post page, Tried to reproduce the issue but it the error throws up randomly - 

`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/asphaltt/public_html/wp-content/plugins/wemail/includes/FrontEnd/FrontEnd.php:31 Stack trace: #0 /home/asphaltt/public_html/wp-includes/class-wp-hook.php(286): WeDevs\WeMail\FrontEnd\FrontEnd->render_form('<p><a href="htt...') #1 /home/asphaltt/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters('<p><a href="htt...', Array) #2 /home/asphaltt/public_html/wp-includes/post-template.php(247): apply_filters('the_content', '<a href="https:...') #3 /home/asphaltt/public_html/wp-content/themes/optimizer/single.php(48): the_content() #4 /home/asphaltt/public_html/wp-includes/template-loader.php(78): include('/home/asphaltt/...') #5 /home/asphaltt/public_html/wp-blog-header.php(19): require_once('/home/asphaltt/...') #6 /home/asphaltt/public_html/index.php(17): require('/home/asphaltt/...') #7 {main} thrown in /home/asphaltt/public_html/wp-content/plugins/wemail/includes/FrontEnd/FrontEnd.php on line 31
`
