### ISSUE TITLE
Remove Postmark From Email Gateways

### ISSUE THREAD

**Issue by lukecav** [weDevsOfficial/wemail#75]
https://getwemail.io/docs/wemail/email-gateways/postmark/

Postmark is for transactional email only and not for bulk email which includes newsletters.
https://postmarkapp.com/support/article/831-why-cant-i-send-bulk-emails

**Comment by tareq1988** [comment]
I guess the brought the feature already: https://postmarkapp.com/blog/api-bulk-the-final-frontier

**Comment by lukecav** [comment]
So if using Postmark with weMail it would send out in batches of up to 500 recipients each batch?

**Comment by tareq1988** [comment]
We don't have the support for batch recipients at this moment, we will be looking forward to integrate that feature. But, weMail handles queueing and sending the emails on it's own infrastructure with as much concurrency as possible, obviously has to be supported by the gateway. So it'll always be faster than any WordPress site or shared hosting.

**Comment by lukecav** [comment]
@tareq1988 
Thanks for the info.
